{{- if .Values.serviceB.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-b
spec:
  type: {{ .Values.serviceB.service.type }}
  ports:
    - port: {{ .Values.serviceB.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: service-b
{{- end }}
