{{- if .Values.serviceA.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  type: {{ .Values.serviceA.service.type }}
  ports:
    - port: {{ .Values.serviceA.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: service-a
{{- end }}
